### ISSUE TITLE
Double quotes makes application to broke.

### ISSUE THREAD

**Issue by DemaPy** [3rd/tsdiagram#21]
Hi, I have managed to found a bug with double quotes.

**Example**

Correct
```
interface ScheduleOptions {
    repeatEvery: string
    daysOfWeek: string[]
    exceptions: string[]
}
```

```
interface ScheduleOptions {
    repeatEvery: string
    'daysOfWeek': string[]
    exceptions: string[]
}
```

Application crashes when in type with Array appeas double quotes.
```
interface ScheduleOptions {
    repeatEvery: string
    "daysOfWeek": string[]
   "exceptions": string[]
}
```

<img width="628" alt="Image" src="https://github.com/user-attachments/assets/5dc674b0-d0d8-461d-b390-1014c1b242db" />

**Comment by 3rd** [comment]
Hey, it's fixed now, thank you for the bug report!

**Comment by DemaPy** [comment]
@3rd bug is still here but it is slightly different. It appears for single double quote and for setters and getters. etc... 

I have created PR: https://github.com/3rd/tsdiagram/pull/22
